name: Scraper Dominios

on:
  schedule:
    - cron: 0 17 * * *  #  Runs at 17:00 UTC every day 
  push:
    branches:
      - master

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64' 

    - name: Install dependencies
      run: pip install -r requirements.txt
           
    - name: Run scraper
      run: python scraper.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
