name: Scraper Dominios

on:
  schedule:
    - cron: 0 2 * * *  #  Runs at 02:00 UTC every day 

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64' 

    - name: Install dependencies
      run: pip install -r requirements.txt
           
    - name: Run scraper
      run: python test_upload.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
